# Generated by Django 4.1.5 on 2023-03-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_name'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='departments.department'),
            preserve_default=False,
        ),
    ]
